services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "4200:4200"

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
